### ISSUE TITLE
Konsole horizontal jittering

### ISSUE THREAD

**Issue by bschepke** [M4444/TMatrix#19]
![tmatrix-konsole](https://user-images.githubusercontent.com/39742666/59970897-e688ac00-9536-11e9-92fd-534acb2b7867.png)

Does not happen in URXVT or Cool Retro Term AppImage.

I am on Debian unstable but was able to reproduce on KDE Neon.

**Comment by M4444** [comment]
Konsole has weird problems dealing with theses characters, even outside TMatrix. I might look into it but I don't think adding something to TMatrix would fix it.

How did you get it to ron on urxvt? Some people had problems with it: #6. Maybe you can help them.

**Comment by bschepke** [comment]
> How did you get it to ron on urxvt? Some people had problems with it: #6. Maybe you can help them.

Same issue as them with block characters in URXVT.
