### ISSUE TITLE
Exec format error.?

### ISSUE THREAD

**Issue by ardentphoenix** [M4444/TMatrix#21]
been getting this when trying to install on rasberry pi, rapsbian os. I know it's running libncurses6.1 not sure if that's the issue, or what needs to be changed so it can find it. 

pi@pi:~/installation $ sudo ./install.sh
pi@pi:~/installation $ tmatrix
-bash: /usr/bin/tmatrix: cannot execute binary file: Exec format error

This is the error when trying to compile from source:
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Curses (missing: CURSES_LIBRARY CURSES_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.13/Modules/FindCurses.cmake:245 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:23 (find_package)

**Comment by ardentphoenix** [comment]
Fixed it by running;
sudo apt-get install libncurses5-dev libncursesw5-dev
Then recompiling.

**Comment by M4444** [comment]
Yes, the issue with the precompiled binary was that it uses `libncurses5`.
I'm not sure about the problem with compiling from source. Did you try installing `libncurses6-dev`?
