### ISSUE TITLE
Misplaced v1.3 tag

### ISSUE THREAD

**Issue by eliasrg** [M4444/TMatrix#23]
The tag `v1.3`currently points to an abandoned commit, which causes the Arch Linux build to classify the current version as 1.2. `v1.3` should probably be changed to point to master.

**Comment by M4444** [comment]
Thanks for catching this, don't know how it happened. Does it work now?

**Comment by M4444** [comment]
Also wanted to ask you if there is a way to set the license of the AUR package to `GPL-2.0-only` so it's synced with other packages?

**Comment by eliasrg** [comment]
It works better now!

The current license name `GPL2` is tied to a directory name in the Arch package [`licenses`](https://www.archlinux.org/packages/core/any/licenses/), so it can't be changed without consequence. However, the convention stated [in the Arch wiki](https://wiki.archlinux.org/index.php/PKGBUILD#license) is that `GPL2` does mean "GPL2 only" (while `GPL` is "GPL2 or later" and `GPL3` is "GPL3 or later").

**Comment by M4444** [comment]
Oh I see, thanks for clarifying!
