### ISSUE TITLE
/usr/share/zsh/site-functions//_tmatrix

### ISSUE THREAD

**Issue by taschenlampe** [M4444/TMatrix#24]
Running a ubuntu-based system:

sudo ./install.sh
[sudo] Password for user: 
install: regular file '/usr/share/zsh/site-functions//_tmatrix' cannot be created: File or directory not found
-> note the // 

In install.sh  I found
ZSH_COMPLETION_DIR="$INSTALL_PREFIX/share/zsh/site-functions/"
Solved by removing the ending "/" + creating the missing dir ; install runs after these little steps-

**Comment by chrisgerman** [comment]
I 2nd this, also having the same issue on Ubuntu 18.04.4 LTS

**Comment by M4444** [comment]
Thanks for reporting this. It should be fixed now.
