### ISSUE TITLE
Doesn't work on Windows WSL

### ISSUE THREAD

**Issue by thisismygitrepo** [M4444/TMatrix#30]
I got a total mess, high consumption of CPU. Win11 WSL, distro: Ubuntu

**Comment by M4444** [comment]
When you say a mess, do you mean anything other than the CPU consumption? This looks like a problem with the terminal emulator, I've certainly seen that in the past. Can try it out with different terminal emulators?

**Comment by M4444** [comment]
The CPU consumption definitely jumps up when running Tmatrix on full screen, even when trying different emulators, but some slow down while some others (e.g. Alacritty) handle it pretty good.
I'll of course continue optimizing Tmatrix in the future but there seems to be some unavoidable CPU overhead in connecting WSL and Windows.
