### ISSUE TITLE
Feature Request: Transparent Background Support

### ISSUE THREAD

**Issue by Sergi-us** [M4444/TMatrix#34]
Hello TMatrix developers,

I am enjoying using TMatrix and appreciate the work put into it. I am currently trying to set it up in a way that it integrates seamlessly with my transparent terminal setup. I noticed that there is no option to make the background of TMatrix transparent, and I think this feature would be a great addition.

Having the ability to run TMatrix with a transparent background would allow the digital rain effect to overlay beautifully with the desktop wallpaper or other applications, enhancing the visual experience.

Thank you for considering this feature request.

Best regards, 

Sergius

**Comment by Sergi-us** [comment]
Hello again,

I am also interested in contributing to TMatrix and was wondering if you could guide me on how to modify the source code to implement transparent background support myself. Could you point me to the part of the code that handles background rendering, or any tips on where to start looking?

Any guidance would be greatly appreciated, as I am keen to contribute to the project and potentially submit a pull request once I manage to implement this feature.

**Comment by M4444** [comment]
Hey, thanks for your lovely words! It's always nice to hear from people enjoying TMatrix and using it in their seutp.

There is already a way to do what you want. If you run tmatrix without any arguments it will have the background set to black but if the default color of your terminal is set to be transparent and you run tmatrix with `--background=default` (or `-c default`) the background will now be transparent.

**Comment by M4444** [comment]
Closing the issue.
If you have any more questions about this feel free to reopen it and we'll discuss further.
