### ISSUE TITLE
Gentoo instructions broken

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [M4444/TMatrix#37]
The current instructions tell to enable repository `bright`, but the repo is not available in the default list of repositories. `eselect repository enable bright` fails: `repository not in repositories.xml`.

Please update the readme to either bring the gentoo instructions up to date or remove the section altogether.

**Comment by M4444** [comment]
Thanks for the heads up.
The `bright` repo was removed so I deleted the Gentoo instructions.
