### ISSUE TITLE
Typo in man page regarding background color 

### ISSUE THREAD

**Issue by sebpardo** [M4444/TMatrix#9]
The man page incorrectly indicates the `-C` argument for changing both letter and background color when changing the background color should be `-c`, see line 78:

https://github.com/M4444/TMatrix/blob/223fb2c3e8170dcd5687d7a85962bed1dd4415ac/tmatrix.6#L6-L12

https://github.com/M4444/TMatrix/blob/223fb2c3e8170dcd5687d7a85962bed1dd4415ac/tmatrix.6#L69-L79

**Comment by M4444** [comment]
Nice catch, thanks! Do you want me to commit the change or would you like to send a pull request?

**Comment by sebpardo** [comment]
Probably easiest and fastest if you do it directly. Thanks for creating this, it's really cool!

**Comment by M4444** [comment]
Thank you, I appreciate it.
The commit is up. thanks for your contribution.
